version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '0527'
      MYSQL_DATABASE: ibbi
    ports:
      - "3307:3306"  # Externo: 3307,  Interno: 3306
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "3000:8000"
    depends_on:
      - db
    environment:
      - DB_USER=root
      - DB_PASS=0527
      - DB_HOST=db  
      - DB_PORT=3306
      - DB_NAME=ibbi  
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
      

volumes:
  mysql_data:
