version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '0527'
      MYSQL_DATABASE: ibbi  # Nome do banco de dados a ser criado
    ports:
      - "3307:3306"  # Porta externa 3307 mapeada para a porta interna 3306
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "3000:8000"
    depends_on:
      - db
    environment:
      - DB_USER=root
      - DB_PASS=0527
      - DB_HOST=db  
      - DB_PORT=3306
      - DB_NAME=ibbi  

volumes:
  mysql_data:
