version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 22052719
      MYSQL_DATABASE: ibbi
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "3000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://root:22052719@db:3306/ibbi  # Ajustado para a porta padrão do MySQL

volumes:
  mysql_data:
